In [521]:
import numpy as np

#### Creating One Dimensional Array

In [522]:
numbers = [1,2,3,4,5,6]
first_array = np.array(numbers)
first_array

array([1, 2, 3, 4, 5, 6])

#### Creating Two Dimensional Array

In [523]:
other_numbers = [[1,2,3],[4,5,6],[7,8,9]]
second_array = np.array(other_numbers)
second_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [524]:
# np.arange(start,stop,increment/decrement)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [525]:
# Creating an Array of 6 0's
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [526]:
# create 2 rows and 3 columns of each element value 0
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [527]:
# one dimensional array of 5 elements where each value is 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [528]:
# 3 rows 4 columns array of 12 elements where each value is 1
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [529]:
# linspace is used for taking n values between two range
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [530]:
# Creating Identity Matrix of 4 columns
np.eye(4) # np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [531]:
# takes 5 random numbers between 0 and 1
np.random.rand(5) # np.random.randn(5)

array([0.44987886, 0.54081282, 0.38487525, 0.1459143 , 0.72163385])

In [532]:
#  takes 5 random integers between 2 and 20
np.random.randint(2,20,5)

array([ 4, 13, 11, 11, 12])

In [533]:
# create two dimensional array from one-dimensional array
some_numbers = [1,2,3,4,5,6,7,8,9]
np.array(some_numbers).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [534]:
another = np.array(some_numbers)
# returns max number of the array
another.max()

9

In [535]:
# returns position/index of max numbre of the array
another.argmax()

8

In [536]:
# Returns minimum of an array
another.min()

1

In [537]:
# Returns position/index of minimum  number 
another.argmin()

0

In [538]:
# data type of array
another.dtype

dtype('int32')

#### N.B : all numpy methods can be applied after converting any list to numpy array

In [539]:
# array slicing array[start_index:stop_index]
# arr[1:] means grab everything from index 1
# arr[:5] means grab everything from index 0 to 5
# arr[2:5] means grab everything from index 2 to 5
# another[::-1] print everything from reverse
another[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [540]:
# As array assignment pass a reference to its value so any change
# to new variable will affect the original array. To get a copy of 
# original array use array.copy() 
third = another.copy()
third

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [541]:
another[0:2] = 200
another 

array([200, 200,   3,   4,   5,   6,   7,   8,   9])

In [542]:
third

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [543]:
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [544]:
#  array_2d[row_slicing_syntax,column_slicing_syntax]
# grab row from 0 to 1 and for every row grab colum 1 to end
array_2d[:2,1:] 

array([[10, 15],
       [25, 30]])

### Boolean Array from Numeric Data array

In [545]:
marks = np.arange(70,100)
marks

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [546]:
# keep track of each item by boolean flag whether they pass the
# condition or not
bool_arr = marks >= 80
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [547]:
# print values of items which became True
marks[bool_arr]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

In [548]:
# another way of doing it
marks[marks >=80]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

In [549]:
another_2d = np.arange(50).reshape(5,10)
another_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [550]:
# lets grab third rows 3 to 6 column values
another_2d[2][3:6]

array([23, 24, 25])

In [551]:
# array[row, column] is short-hand of array[row][column]
another_2d[1,1] # another_2d[1][1]

11

### Array operations

In [552]:
simple_arr = np.arange(1,11)
simple_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [553]:
# simple_arr + simple_arr 
# simple_arr - simple_arr
# simple_arr * simple_arr
# simple_arr / simple_arr
simple_arr + simple_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [554]:
# simple_arr + 100
# simple_arr - 100
# simple_arr * 100
# simple_arr / 100
simple_arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

### Universal Methods

In [555]:
# square root of each element
np.sqrt(simple_arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [556]:
# arithmatic mean of array
np.mean(simple_arr)

5.5

In [557]:
# summation of all elements 
np.sum(simple_arr)

55

In [558]:
np.max(simple_arr)

10

In [559]:
np.min(simple_arr)

1

In [560]:
# exponential of all elements
np.exp(simple_arr) 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [561]:
np.log(simple_arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [562]:
np.sin(simple_arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [563]:
# create an array of 10 5's
# process : 01
num = [5]*10
num

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [564]:
# process : 02 list comprehension method
another_num = [5 for i in range(10)]
another_num

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [565]:
# process : 03
np.full((10),5)
# np.full ((2,2),5) will create 2x2 matrix of each element value 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### Some numpy Array Methods

In [566]:
demo = np.array([4,6,8,10])
print(demo)

[ 4  6  8 10]


In [567]:
# get dimension
demo.ndim

1

In [568]:
# get size of the array
demo.size

4

In [569]:
#get how many bytes
demo.nbytes

16

In [570]:
# get Shape 
demo.shape

(4,)

In [571]:
# get item size
demo.itemsize

4

In [572]:
# demo.nbytes = demo.itemsize * demo.size
demo.itemsize * demo.size

16

In [573]:
# Get data type
demo.dtype

dtype('int32')

### Matrix Multiplication

In [574]:
# Matrix Multiplication
mat0 = np.full((2,2),1)
print(mat0)
mat1 = np.full((2,2),2)
print(mat1)

np.matmul(mat0,mat1)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


array([[4, 4],
       [4, 4]])

### Determinant of a Matrix

In [575]:
my_matrix = np.identity(3)
print(my_matrix)
determinant = np.linalg.det(my_matrix)
print(f'Determinant : {determinant}')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant : 1.0


### Reading data from txt file 

In [576]:
# delimiter says for getting which character numbers will be seperated
# filedata = np.genfromtxt('filename.txt',delimiter = ',')